### ISSUE TITLE
View 下的第二，第三張圖片是如何生成的？

### ISSUE THREAD

**Issue by Ncerzzk** [KitSprout/LocalPositionSystem#1]
hello!对此很感兴趣，不知道是用什么办法生成的？

**Comment by hom-wang** [comment]
altium designer 16 之後新增的一種檔案 draftsman document，再配合小畫家做的

關於 draftsman document 可以參考官方說明
http://www.altium.com/documentation/16.1/display/ADES/((Draftsman))_AD
