### ISSUE TITLE
Issue with USB to serial on F072C

### ISSUE THREAD

**Issue by ww9980** [KitSprout/LocalPositionSystem#2]
Hi Hom,

It seems that the project for F072C is not included. I presume it's a USB to serial? Could you give some hints on implementing? 

Cheers,
ww9980

**Comment by hom-wang** [comment]
Hi ww9980, 

It's a jlink-ob with virtual com port (VCP). There is more detail in [this](http://akb77.com/g/stm32/jlink-ob/) and [this](https://www.amobbs.com/thread-5648404-1-1.html).

Hope it helps : )
Hom

**Comment by ww9980** [comment]
Hi Hom,

I got it. Issue resolved. 

ww9980
